begin;

do $$
declare
  unsafe_tables text;
begin
  select string_agg(format('%I.%I', schemaname, tablename), ', ' order by schemaname, tablename)
    into unsafe_tables
    from pg_tables
   where schemaname = 'public'
     and not rowsecurity;

  if unsafe_tables is not null then
    raise exception 'Stop: RLS is disabled on existing public tables: %', unsafe_tables;
  end if;
end;
$$;

do $$
begin
  if to_regclass('public.demo_projects') is not null
     and obj_description(to_regclass('public.demo_projects'), 'pg_class')
         is distinct from 'vibies:issue-13-demo-projects' then
    raise exception 'Stop: public.demo_projects is not owned by the Vibies issue 13 demo setup';
  end if;
end;
$$;

create table if not exists public.demo_projects (
  id bigint generated by default as identity (start with 2) primary key,
  title text not null,
  summary text not null,
  created_at timestamptz not null default now()
);

comment on table public.demo_projects is 'vibies:issue-13-demo-projects';

insert into public.demo_projects (id, title, summary)
values (
  1,
  'Vibies',
  'A fictional community where beginners build and share small projects.'
)
on conflict (id) do nothing;

revoke all privileges on table public.demo_projects from public, anon, authenticated;
revoke all privileges on sequence public.demo_projects_id_seq from public, anon, authenticated;
grant select on table public.demo_projects to anon;

alter table public.demo_projects enable row level security;

do $$
begin
  if exists (
    select 1
      from pg_policies
     where schemaname = 'public'
       and tablename = 'demo_projects'
       and policyname <> 'demo_projects_anon_select'
  ) then
    raise exception 'Stop: public.demo_projects has a policy outside this demo setup';
  end if;
end;
$$;

drop policy if exists demo_projects_anon_select on public.demo_projects;
create policy demo_projects_anon_select
  on public.demo_projects
  for select
  to anon
  using (true);

commit;
