export type WikiEntry = {
  id: string;
  title: string;
  topic: string;
  where: "shell" | "tmux" | "Codex" | "SQL Editor" | "browser";
  command?: string;
  keys?: string;
  usage: string;
  prerequisites: string;
  placeholders?: string;
  result: string;
  sources: { file: string; location: string }[];
  guide?: { label: string; href: string };
};

const replaceBrackets = "Replace each value in [brackets], including the brackets, before you run the command.";
const repository = "https://github.com/vibies-club/vibies/blob/main";

export const wikiEntries: WikiEntry[] = [
  {
    id: "wsl-install",
    title: "Install WSL on Windows",
    topic: "Terminal",
    where: "shell",
    command: "wsl --install",
    usage: "Run this once in PowerShell on Windows, then restart the computer and finish the Ubuntu setup.",
    prerequisites: "Windows and PowerShell with administrator access.",
    result: "Installs WSL and tells you when a restart or setup step is required.",
    sources: [{ file: "vibies-session-1.html", location: "slide 37" }],
  },
  {
    id: "ubuntu-install-git",
    title: "Install Git in Ubuntu",
    topic: "Terminal",
    where: "shell",
    command: "sudo apt install git",
    usage: "Run this in Ubuntu or WSL when Git is missing.",
    prerequisites: "Ubuntu or Ubuntu in WSL, with sudo access.",
    result: "Installs Git or reports why the package could not be installed.",
    sources: [{ file: "vibies-session-1.html", location: "slide 37" }],
  },
  {
    id: "git-version",
    title: "Check the Git version",
    topic: "Terminal",
    where: "shell",
    command: "git --version",
    usage: "Use this setup check to confirm that the Git command is available.",
    prerequisites: "Git installed.",
    result: "Prints the installed Git version or stops with a command-not-found error.",
    sources: [
      { file: "vibies-session-2.html", location: "slide 2" },
      { file: "vibies-session-catchup.html", location: "slide 9" },
    ],
  },
  {
    id: "tmux-version",
    title: "Check the tmux version",
    topic: "Terminal",
    where: "shell",
    command: "tmux -V",
    usage: "Use this setup check to confirm that tmux is available.",
    prerequisites: "tmux installed.",
    result: "Prints the installed tmux version or stops with a command-not-found error.",
    sources: [{ file: "vibies-session-2.html", location: "slide 2" }],
  },
  {
    id: "pwd",
    title: "Show the current folder",
    topic: "Terminal",
    where: "shell",
    command: "pwd",
    usage: "Run this before a file command when you need to confirm your current location.",
    prerequisites: "None",
    result: "Prints the full path of the current folder.",
    sources: [
      { file: "vibies-session-2.html", location: "slides 18 and 25" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, Paths and moving around" },
    ],
  },
  {
    id: "ls",
    title: "List files and folders",
    topic: "Terminal",
    where: "shell",
    command: "ls",
    usage: "Use this to see the items in the current folder. The taught ls -la variant also shows hidden items and details.",
    prerequisites: "None",
    result: "Prints the visible files and folders in the current folder.",
    sources: [
      { file: "vibies-session-2.html", location: "slides 16 and 25" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, Paths and moving around" },
    ],
  },
  {
    id: "cd-folder",
    title: "Enter a folder",
    topic: "Terminal",
    where: "shell",
    command: "cd [folder]",
    usage: "Move into a child folder. Put quotes around a path that contains spaces.",
    prerequisites: "The folder exists at the path you give.",
    placeholders: replaceBrackets,
    result: "Changes the shell's current folder or reports that the path does not exist.",
    sources: [
      { file: "vibies-session-2.html", location: "slides 22, 25, and 27" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, Paths and moving around" },
    ],
  },
  {
    id: "cd-parent",
    title: "Move to the parent folder",
    topic: "Terminal",
    where: "shell",
    command: "cd ..",
    usage: "Move up one folder from your current location.",
    prerequisites: "None",
    result: "Changes the current folder to its parent.",
    sources: [
      { file: "vibies-session-2.html", location: "slides 23 and 25" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, Paths and moving around" },
    ],
  },
  {
    id: "cd-home",
    title: "Move to the home folder",
    topic: "Terminal",
    where: "shell",
    command: "cd ~",
    usage: "Return to your user home folder from any location.",
    prerequisites: "None",
    result: "Changes the current folder to your home folder.",
    sources: [
      { file: "vibies-session-2.html", location: "slides 21 and 25" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, Paths and moving around" },
    ],
  },
  {
    id: "mkdir",
    title: "Create a folder",
    topic: "Terminal",
    where: "shell",
    command: "mkdir [name]",
    usage: "Create one folder inside the current folder.",
    prerequisites: "Write access in the current folder.",
    placeholders: replaceBrackets,
    result: "Creates the named folder or stops if that name cannot be created.",
    sources: [
      { file: "vibies-session-2.html", location: "slides 16 and 26" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, Files and folders" },
    ],
  },
  {
    id: "touch-file",
    title: "Create an empty file",
    topic: "Terminal",
    where: "shell",
    command: "touch [name].md",
    usage: "Create an empty Markdown file, or update its modified time if it already exists.",
    prerequisites: "Write access in the current folder.",
    placeholders: replaceBrackets,
    result: "Creates the file when it is absent and leaves existing contents unchanged.",
    sources: [
      { file: "vibies-session-2.html", location: "slide 26" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, Files and folders" },
    ],
  },
  {
    id: "copy-file",
    title: "Copy a file",
    topic: "Terminal",
    where: "shell",
    command: "cp [from] [to]",
    usage: "Copy one file to a new path. Check the destination first because an existing file can be replaced.",
    prerequisites: "The source file exists and the destination is writable.",
    placeholders: replaceBrackets,
    result: "Creates the destination copy or reports why the copy failed.",
    sources: [
      { file: "vibies-session-2.html", location: "slide 26" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, Files and folders" },
    ],
  },
  {
    id: "move-file",
    title: "Move or rename a file",
    topic: "Terminal",
    where: "shell",
    command: "mv [old] [new]",
    usage: "Move a file to another path or give it a new name. Check the destination first.",
    prerequisites: "The source exists and the destination is writable.",
    placeholders: replaceBrackets,
    result: "Moves the source to the destination or reports why the move failed.",
    sources: [
      { file: "vibies-session-2.html", location: "slide 26" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, Files and folders" },
    ],
  },
  {
    id: "cat-file",
    title: "Show a text file",
    topic: "Terminal",
    where: "shell",
    command: "cat [file]",
    usage: "Print a small text file in the terminal.",
    prerequisites: "The file exists and is readable.",
    placeholders: replaceBrackets,
    result: "Prints the file contents or reports why the file cannot be read.",
    sources: [
      { file: "vibies-session-2.html", location: "slide 26" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, Files and folders" },
    ],
  },
  {
    id: "clear-terminal",
    title: "Clear the terminal screen",
    topic: "Terminal",
    where: "shell",
    command: "clear",
    usage: "Clear visible terminal output when you want a clean screen.",
    prerequisites: "None",
    result: "Clears the visible screen while keeping shell history available.",
    sources: [
      { file: "vibies-session-2.html", location: "slide 26" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, Files and folders" },
    ],
  },
  {
    id: "code-current-folder",
    title: "Open the current folder in VS Code",
    topic: "Terminal",
    where: "shell",
    command: "code .",
    usage: "Open the folder where the shell is currently standing.",
    prerequisites: "VS Code installed with its code command available in PATH.",
    result: "Opens the current folder in VS Code or reports that the code command is missing.",
    sources: [
      { file: "vibies-session-2.html", location: "slides 2 and 23" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, Files and folders" },
    ],
  },
  {
    id: "shell-tab-completion",
    title: "Complete a name with Tab",
    topic: "Terminal",
    where: "shell",
    keys: "Tab",
    usage: "Press Tab while typing a path or command to complete an available match.",
    prerequisites: "A partially typed path or command in an interactive shell.",
    result: "Completes the match or shows possible matches.",
    sources: [{ file: "vibies-cheatsheet.pdf", location: "page 1, Tab and up arrow" }],
  },
  {
    id: "shell-command-history",
    title: "Recall the previous command",
    topic: "Terminal",
    where: "shell",
    keys: "Up arrow",
    usage: "Press the up arrow to put an earlier command back on the prompt for review or editing.",
    prerequisites: "An interactive shell with command history.",
    result: "Shows the previous command without running it.",
    sources: [{ file: "vibies-cheatsheet.pdf", location: "page 1, Tab and up arrow" }],
  },
  {
    id: "tmux-new-session",
    title: "Create a tmux session",
    topic: "tmux",
    where: "shell",
    command: "tmux new -s [name]",
    usage: "Start a named workspace that can keep running after you detach.",
    prerequisites: "tmux installed.",
    placeholders: replaceBrackets,
    result: "Creates the named session and opens it, or reports a name conflict.",
    sources: [
      { file: "vibies-session-2.html", location: "slide 32" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, tmux cockpit" },
    ],
  },
  {
    id: "tmux-detach",
    title: "Detach from tmux",
    topic: "tmux",
    where: "tmux",
    keys: "Ctrl+b, then d",
    usage: "Press Ctrl+b, release it, then press d to leave the session running.",
    prerequisites: "You are inside a tmux session.",
    result: "Returns to the outer shell while the tmux session keeps running.",
    sources: [
      { file: "vibies-session-2.html", location: "slides 31 and 32" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, tmux cockpit" },
    ],
  },
  {
    id: "tmux-list-sessions",
    title: "List tmux sessions",
    topic: "tmux",
    where: "shell",
    command: "tmux ls",
    usage: "Check which tmux sessions are running.",
    prerequisites: "tmux installed.",
    result: "Prints running sessions or reports that no server is running.",
    sources: [
      { file: "vibies-session-2.html", location: "slide 32" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, tmux cockpit" },
    ],
  },
  {
    id: "tmux-attach-session",
    title: "Return to a tmux session",
    topic: "tmux",
    where: "shell",
    command: "tmux attach -t [name]",
    usage: "Open an existing named session again.",
    prerequisites: "The named tmux session is running.",
    placeholders: replaceBrackets,
    result: "Attaches to the session or reports that the session cannot be found.",
    sources: [
      { file: "vibies-session-2.html", location: "slide 32" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, tmux cockpit" },
    ],
  },
  {
    id: "tmux-kill-session",
    title: "End a tmux session",
    topic: "tmux",
    where: "shell",
    command: "tmux kill-session -t [name]",
    usage: "End a named session after you confirm that its running work can stop.",
    prerequisites: "The named tmux session exists.",
    placeholders: replaceBrackets,
    result: "Stops the session and the processes running inside it.",
    sources: [{ file: "vibies-session-2.html", location: "slide 32" }],
  },
  {
    id: "tmux-split-pane",
    title: "Split a tmux pane side by side",
    topic: "tmux",
    where: "tmux",
    keys: "Ctrl+b, then %",
    usage: "Press Ctrl+b, release it, then press % to create a pane beside the current pane.",
    prerequisites: "You are inside a tmux session.",
    result: "Splits the current tmux area into left and right panes.",
    sources: [
      { file: "vibies-session-2.html", location: "slides 31 and 33" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, tmux cockpit" },
    ],
  },
  {
    id: "tmux-split-pane-top-bottom",
    title: "Split a tmux pane top and bottom",
    topic: "tmux",
    where: "tmux",
    keys: "Ctrl+b, then \"",
    usage: "Press Ctrl+b, release it, then press the double quote key.",
    prerequisites: "You are inside a tmux session.",
    result: "Splits the current tmux area into top and bottom panes.",
    sources: [
      { file: "vibies-session-2.html", location: "slide 33" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, tmux cockpit" },
    ],
  },
  {
    id: "tmux-move-pane",
    title: "Move between tmux panes",
    topic: "tmux",
    where: "tmux",
    keys: "Ctrl+b, then arrow key",
    usage: "Press Ctrl+b, release it, then press the arrow that points to the pane you want.",
    prerequisites: "The tmux window has more than one pane.",
    result: "Moves keyboard focus to the pane in that direction.",
    sources: [
      { file: "vibies-session-2.html", location: "slide 33" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, tmux cockpit" },
    ],
  },
  {
    id: "tmux-zoom-pane",
    title: "Zoom a tmux pane",
    topic: "tmux",
    where: "tmux",
    keys: "Ctrl+b, then z",
    usage: "Use the same shortcut to enter and leave full-pane view.",
    prerequisites: "You are inside a tmux session.",
    result: "Toggles the current pane between normal and full-window size.",
    sources: [
      { file: "vibies-session-2.html", location: "slide 33" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, tmux cockpit" },
    ],
  },
  {
    id: "tmux-close-pane",
    title: "Close a tmux pane",
    topic: "tmux",
    where: "tmux",
    keys: "Ctrl+b, then x",
    usage: "Close the current pane only after you confirm that its running process can stop.",
    prerequisites: "You are inside a tmux session.",
    result: "Asks for confirmation, then closes the pane and its process when you answer yes.",
    sources: [
      { file: "vibies-session-2.html", location: "slide 33" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, tmux cockpit" },
    ],
  },
  {
    id: "tmux-new-window",
    title: "Create a tmux window",
    topic: "tmux",
    where: "tmux",
    keys: "Ctrl+b, then c",
    usage: "Create another full-screen terminal window inside the current session.",
    prerequisites: "You are inside a tmux session.",
    result: "Creates a new tmux window and selects it.",
    sources: [{ file: "vibies-session-2.html", location: "slide 33" }],
  },
  {
    id: "tmux-change-window",
    title: "Change tmux windows",
    topic: "tmux",
    where: "tmux",
    keys: "Ctrl+b, then n or p",
    usage: "Use n for the next window or p for the previous window.",
    prerequisites: "The tmux session has more than one window.",
    result: "Selects the next or previous tmux window.",
    sources: [{ file: "vibies-session-2.html", location: "slide 33" }],
  },
  {
    id: "tmux-jump-window",
    title: "Jump to a numbered tmux window",
    topic: "tmux",
    where: "tmux",
    keys: "Ctrl+b, then 0-9",
    usage: "Press the number shown for the tmux window you want.",
    prerequisites: "A tmux window with that number exists.",
    result: "Selects the numbered window.",
    sources: [{ file: "vibies-session-2.html", location: "slide 33" }],
  },
  {
    id: "tmux-scroll-mode",
    title: "Enter tmux scroll mode",
    topic: "tmux",
    where: "tmux",
    keys: "Ctrl+b, then [",
    usage: "The final [ is a literal key. Use arrow keys or Page Up after scroll mode opens.",
    prerequisites: "You are inside a tmux session.",
    result: "Opens tmux copy mode so you can move through earlier output.",
    sources: [
      { file: "vibies-session-2.html", location: "slide 34" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, tmux cockpit" },
    ],
  },
  {
    id: "tmux-quit-scroll",
    title: "Leave tmux scroll mode",
    topic: "tmux",
    where: "tmux",
    keys: "q",
    usage: "Press q when tmux is in scroll mode and normal typing appears stuck.",
    prerequisites: "tmux scroll mode is open.",
    result: "Closes scroll mode and returns control to the shell in the pane.",
    sources: [
      { file: "vibies-session-2.html", location: "slide 34" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, tmux cockpit" },
    ],
  },
  {
    id: "tmux-enable-mouse",
    title: "Enable the tmux mouse",
    topic: "tmux",
    where: "shell",
    command: "echo \"set -g mouse on\" >> ~/.tmux.conf",
    usage: "Run this once to add mouse support to your tmux configuration. Check the file first to avoid a duplicate line.",
    prerequisites: "tmux installed and permission to edit your user tmux configuration.",
    result: "Appends the mouse setting to your user tmux configuration.",
    sources: [{ file: "vibies-cheatsheet.pdf", location: "page 1, tmux 2-line config" }],
  },
  {
    id: "tmux-reload-config",
    title: "Reload the tmux configuration",
    topic: "tmux",
    where: "shell",
    command: "tmux source-file ~/.tmux.conf",
    usage: "Apply saved tmux configuration changes without restarting the session.",
    prerequisites: "A running tmux server and a readable ~/.tmux.conf file.",
    result: "Reloads the configuration or reports the invalid setting or missing file.",
    sources: [
      { file: "vibies-session-2.html", location: "slide 34" },
      { file: "vibies-cheatsheet.pdf", location: "page 1, tmux 2-line config" },
    ],
  },
  {
    id: "git-config-name",
    title: "Set the Git commit nickname",
    topic: "Git",
    where: "shell",
    command: "git config --global user.name \"[your nickname]\"",
    usage: "The --global form affects repositories on this computer. For one repository, use git config user.name \"[your nickname]\". Run git config user.name to read its effective value.",
    prerequisites: "Git installed and a chosen public nickname.",
    placeholders: replaceBrackets,
    result: "Saves the nickname in your global Git configuration.",
    sources: [
      { file: "vibies-session-3.html", location: "slide 5, personal value replaced" },
      { file: "vibies-session-catchup.html", location: "slide 15, local variant" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, Git save system" },
    ],
  },
  {
    id: "git-config-email",
    title: "Set the Git no-reply email",
    topic: "Git",
    where: "shell",
    command: "git config --global user.email \"[your GitHub no-reply email]\"",
    usage: "The --global form affects repositories on this computer. For one repository, use git config user.email \"[your GitHub no-reply email]\". Run git config user.email to read its effective value.",
    prerequisites: "Git installed and your no-reply address from GitHub email settings.",
    placeholders: replaceBrackets,
    result: "Saves the no-reply address in your global Git configuration.",
    sources: [
      { file: "vibies-session-3.html", location: "slide 5, personal value replaced" },
      { file: "vibies-session-catchup.html", location: "slide 15, local variant" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, Git save system" },
    ],
  },
  {
    id: "git-default-main",
    title: "Use main for new Git repositories",
    topic: "Git",
    where: "shell",
    command: "git config --global init.defaultBranch main",
    usage: "Set the initial branch name for repositories that you create later.",
    prerequisites: "Git installed.",
    result: "Stores main as the default initial branch name.",
    sources: [
      { file: "vibies-session-3.html", location: "slide 5" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, Git save system" },
    ],
  },
  {
    id: "git-init",
    title: "Start a Git repository",
    topic: "Git",
    where: "shell",
    command: "git init",
    usage: "Start Git history in the current project folder.",
    prerequisites: "Confirm the current folder with pwd and check that it is the intended project.",
    result: "Creates or reinitializes the current folder's .git metadata.",
    sources: [
      { file: "vibies-session-3.html", location: "slide 6" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, Git save system" },
    ],
  },
  {
    id: "git-init-main",
    title: "Start a Git repository on main",
    topic: "Git",
    where: "shell",
    command: "git init -b main",
    usage: "Start a new repository and name its first branch main in one command.",
    prerequisites: "Confirm the current folder is a new project without a Git repository.",
    result: "Creates Git metadata with main as the current branch.",
    sources: [{ file: "vibies-session-catchup.html", location: "slide 15" }],
  },
  {
    id: "git-rename-main",
    title: "Rename the current Git branch to main",
    topic: "Git",
    where: "shell",
    command: "git branch -m main",
    usage: "Rename the current branch when a new repository started with another branch name.",
    prerequisites: "You are in a new personal repository on its initial branch. Never use this to rename a shared feature branch.",
    result: "Renames the current branch to main.",
    sources: [
      { file: "vibies-session-3.html", location: "slide 6" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, Git save system" },
    ],
  },
  {
    id: "git-status",
    title: "Check Git status",
    topic: "Git",
    where: "shell",
    command: "git status",
    usage: "Use this as your compass before and after changes. It shows the branch and file states.",
    prerequisites: "You are inside a Git repository.",
    result: "Prints the current branch and the staged, changed, and untracked files.",
    sources: [
      { file: "vibies-session-3.html", location: "slides 6, 8, 10, and 15" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, Git save system" },
    ],
  },
  {
    id: "git-current-branch",
    title: "Show the current Git branch",
    topic: "Git",
    where: "shell",
    command: "git branch --show-current",
    usage: "Print only the current branch name when you need a short branch check.",
    prerequisites: "You are inside a Git repository.",
    result: "Prints the current branch name, or prints nothing in a detached state.",
    sources: [{ file: "vibies-session-catchup.html", location: "slide 15" }],
  },
  {
    id: "git-add-all",
    title: "Stage current project changes",
    topic: "Git",
    where: "shell",
    command: "git add .",
    usage: "Stage changes below the current folder, then read git diff --staged before committing.",
    prerequisites: "You reviewed git status and intend to stage every shown path in this folder.",
    result: "Adds the selected changes to the staging area.",
    sources: [
      { file: "vibies-session-3.html", location: "slides 8 and 11" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, Git save system" },
    ],
  },
  {
    id: "git-add-files",
    title: "Stage named files",
    topic: "Git",
    where: "shell",
    command: "git add [file]",
    usage: "Stage only the named path. Repeat the path argument when the approved change contains more than one file.",
    prerequisites: "You reviewed git status and the named paths belong to the approved change.",
    placeholders: replaceBrackets,
    result: "Adds the named path to the staging area or reports why it could not be staged.",
    sources: [
      { file: "vibies-session-9.html", location: "slide 9, named documentation path replaced" },
      { file: "vibies-session-10.html", location: "slide 7, named documentation path replaced" },
      { file: "vibies-session-catchup.html", location: "slide 31, named paths replaced" },
    ],
  },
  {
    id: "git-diff",
    title: "Read unstaged Git changes",
    topic: "Git",
    where: "shell",
    command: "git diff",
    usage: "Review changed lines that are still outside the staging area.",
    prerequisites: "You are inside a Git repository.",
    result: "Prints unstaged differences and changes no files.",
    sources: [{ file: "vibies-session-catchup.html", location: "slides 19 and 31" }],
  },
  {
    id: "git-diff-staged",
    title: "Read staged Git changes",
    topic: "Git",
    where: "shell",
    command: "git diff --staged",
    usage: "Review the exact staged diff before you create a commit.",
    prerequisites: "You are inside a Git repository.",
    result: "Prints staged differences and changes no files.",
    sources: [
      { file: "vibies-session-3.html", location: "slide 11" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, Git save system" },
    ],
  },
  {
    id: "git-commit",
    title: "Commit staged changes",
    topic: "Git",
    where: "shell",
    command: "git commit -m \"[what changed]\"",
    usage: "Save the staged snapshot with a short message that states the result.",
    prerequisites: "The staged diff contains only the intended change.",
    placeholders: replaceBrackets,
    result: "Creates a local commit or reports why no commit was made.",
    sources: [
      { file: "vibies-session-3.html", location: "slides 8 and 11" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, Git save system" },
    ],
  },
  {
    id: "git-log-oneline",
    title: "Read the short Git history",
    topic: "Git",
    where: "shell",
    command: "git log --oneline",
    usage: "Read one short line for each commit. Add -3 when you only need the latest three.",
    prerequisites: "The Git repository has at least one commit.",
    result: "Prints the commit history in compact form and changes no files.",
    sources: [
      { file: "vibies-session-3.html", location: "slide 13" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, Git save system" },
    ],
  },
  {
    id: "git-remote-list",
    title: "Show Git remotes",
    topic: "Git",
    where: "shell",
    command: "git remote -v",
    usage: "Inspect remote names and URLs before you add or change a remote.",
    prerequisites: "You are inside a Git repository.",
    result: "Prints fetch and push URLs for configured remotes, or prints nothing when none exist.",
    sources: [{ file: "vibies-session-catchup.html", location: "slide 22" }],
  },
  {
    id: "git-remote-add",
    title: "Add a GitHub remote",
    topic: "Git",
    where: "shell",
    command: "git remote add origin [repository URL]",
    usage: "Link the local repository to an existing empty GitHub repository after you inspect current remotes.",
    prerequisites: "The GitHub repository exists and no origin remote is already configured.",
    placeholders: replaceBrackets,
    result: "Adds the origin remote or stops if that remote name already exists.",
    sources: [
      { file: "vibies-session-3.html", location: "slide 9, personal URL replaced" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, GitHub going online" },
    ],
  },
  {
    id: "git-push-upstream",
    title: "Push a branch and set its upstream",
    topic: "Git",
    where: "shell",
    command: "git push -u origin [branch]",
    usage: "Upload a branch for the first time and connect it to the matching origin branch.",
    prerequisites: "The intended commit is on the current feature branch and origin is correct.",
    placeholders: replaceBrackets,
    result: "Uploads the branch and records its upstream, or reports why the push failed.",
    sources: [
      { file: "vibies-session-3.html", location: "slides 9 and 11" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, GitHub going online" },
    ],
  },
  {
    id: "git-push",
    title: "Push later commits",
    topic: "Git",
    where: "shell",
    command: "git push",
    usage: "Upload new commits after the current branch already has an upstream.",
    prerequisites: "The current feature branch has the intended upstream and reviewed commits.",
    result: "Uploads new commits or reports why the remote rejected the push.",
    sources: [{ file: "vibies-cheatsheet.pdf", location: "page 2, GitHub going online" }],
  },
  {
    id: "git-switch-main",
    title: "Switch to main",
    topic: "Git",
    where: "shell",
    command: "git switch main",
    usage: "Move to the local main branch before pulling reviewed changes. Shared Vibies work reaches main through a reviewed PR.",
    prerequisites: "Local changes are safe and the repository has a main branch.",
    result: "Checks out main or stops when local changes prevent a safe switch.",
    sources: [
      { file: "vibies-session-3.html", location: "slide 13" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, GitHub going online" },
    ],
    guide: { label: "Vibies contribution workflow", href: `${repository}/CONTRIBUTING.md#the-workflow` },
  },
  {
    id: "git-pull",
    title: "Pull remote changes",
    topic: "Git",
    where: "shell",
    command: "git pull",
    usage: "Download and integrate the current branch's upstream changes. For shared Vibies main, use git pull --ff-only and stop if histories diverge.",
    prerequisites: "The current branch has the correct upstream and the working tree is safe to update.",
    result: "Updates the local branch or reports a conflict or connection problem.",
    sources: [
      { file: "vibies-session-3.html", location: "slide 13" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, GitHub going online" },
    ],
  },
  {
    id: "git-pull-ff-only",
    title: "Pull without creating a merge commit",
    topic: "Git",
    where: "shell",
    command: "git pull --ff-only",
    usage: "Update a branch only when Git can move it straight forward.",
    prerequisites: "The current branch has the correct upstream and a clean working tree.",
    result: "Fast-forwards the branch or stops when histories have diverged.",
    sources: [{ file: "vibies-session-catchup.html", location: "slides 27 and 35" }],
  },
  {
    id: "git-switch-feature",
    title: "Create a feature branch",
    topic: "Git",
    where: "shell",
    command: "git switch -c feature/[name]",
    usage: "Create and enter a branch for one approved issue. Shared Vibies work must use a feature branch and reviewed PR.",
    prerequisites: "Start from the intended clean base branch.",
    placeholders: replaceBrackets,
    result: "Creates the named feature branch and switches to it, or reports a name conflict.",
    sources: [
      { file: "vibies-session-3.html", location: "slide 10" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, GitHub going online" },
    ],
    guide: { label: "Vibies contribution workflow", href: `${repository}/CONTRIBUTING.md#the-workflow` },
  },
  {
    id: "gh-auth-login",
    title: "Sign in with GitHub CLI",
    topic: "GitHub",
    where: "shell",
    command: "gh auth login",
    usage: "Start GitHub CLI sign-in. Choose GitHub.com, HTTPS, and browser sign-in for the class setup.",
    prerequisites: "GitHub CLI installed and a GitHub account.",
    result: "Starts the supported sign-in flow or reports why authentication could not start.",
    sources: [
      { file: "vibies-session-catchup.html", location: "slide 9" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, GitHub going online" },
    ],
  },
  {
    id: "gh-auth-setup-git",
    title: "Use GitHub CLI credentials for Git",
    topic: "GitHub",
    where: "shell",
    command: "gh auth setup-git",
    usage: "Configure Git to use the credentials managed by GitHub CLI.",
    prerequisites: "A completed gh auth login session.",
    result: "Configures Git credential use or reports why setup failed.",
    sources: [{ file: "vibies-session-catchup.html", location: "slide 9" }],
  },
  {
    id: "gh-auth-status",
    title: "Check GitHub CLI sign-in",
    topic: "GitHub",
    where: "shell",
    command: "gh auth status",
    usage: "Confirm which GitHub account and host the CLI will use before a push.",
    prerequisites: "GitHub CLI installed.",
    result: "Shows the active authentication state or reports that sign-in is required.",
    sources: [
      { file: "vibies-session-3.html", location: "slide 2" },
      { file: "vibies-session-catchup.html", location: "slide 9" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, GitHub going online" },
    ],
  },
  {
    id: "github-pull-request",
    title: "Open a reviewed pull request",
    topic: "GitHub",
    where: "browser",
    usage: "Open a pull request from one feature branch to main. Link the issue, record the checks, and wait for Member review.",
    prerequisites: "The approved change is pushed on its feature branch and its proof is ready.",
    result: "Creates a review page for the diff, checks, Preview, and merge decision.",
    sources: [
      { file: "vibies-session-3.html", location: "slide 12" },
      { file: "vibies-session-8.html", location: "slides 12 to 14" },
      { file: "vibies-session-catchup.html", location: "slides 31 to 34" },
    ],
    guide: { label: "Vibies contribution workflow", href: `${repository}/CONTRIBUTING.md#the-workflow` },
  },
  {
    id: "codex-install",
    title: "Install Codex CLI",
    topic: "Codex",
    where: "shell",
    command: "npm install -g @openai/codex",
    usage: "Install Codex CLI globally when the codex command is missing.",
    prerequisites: "A supported Node.js and npm installation.",
    result: "Installs the codex command or reports why installation failed.",
    sources: [{ file: "vibies-session-catchup.html", location: "slide 9" }],
  },
  {
    id: "codex-login",
    title: "Sign in to Codex CLI",
    topic: "Codex",
    where: "shell",
    command: "codex login",
    usage: "Start the one-time Codex sign-in flow for your ChatGPT account.",
    prerequisites: "Codex CLI installed and a supported ChatGPT account.",
    result: "Starts sign-in and reports whether Codex saved the session.",
    sources: [{ file: "vibies-cheatsheet.pdf", location: "page 2, Codex agent" }],
  },
  {
    id: "codex-version",
    title: "Check the Codex version",
    topic: "Codex",
    where: "shell",
    command: "codex --version",
    usage: "Confirm that the Codex command is installed and available.",
    prerequisites: "Codex CLI installed.",
    result: "Prints the installed Codex version or stops with a command-not-found error.",
    sources: [
      { file: "vibies-session-4.html", location: "slide 2" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, Codex agent" },
    ],
  },
  {
    id: "codex-start",
    title: "Start Codex in a repository",
    topic: "Codex",
    where: "shell",
    command: "codex",
    usage: "Run this from the project folder so Codex can read that repository's instructions and files.",
    prerequisites: "Codex CLI installed, signed in, and the shell is in the intended project folder.",
    result: "Starts an interactive Codex session or reports why it cannot start.",
    sources: [
      { file: "vibies-session-4.html", location: "slide 6" },
      { file: "vibies-cheatsheet.pdf", location: "page 2, Codex agent" },
    ],
  },
  {
    id: "codex-grill",
    title: "Grill an issue in Codex",
    topic: "Codex",
    where: "Codex",
    command: "$grill-me",
    usage: "Invoke the installed skill to resolve implementation-changing questions before the issue becomes Ready.",
    prerequisites: "The grill-me skill is installed and a draft issue or plan is available.",
    result: "Starts the issue interview and continues until the material choices are resolved.",
    sources: [
      { file: "vibies-session-6.html", location: "slides 7, 8, and 10" },
      { file: "vibies-session-catchup.html", location: "slides 18 and 26" },
    ],
  },
  {
    id: "codex-graphify",
    title: "Create a code graph with Graphify",
    topic: "Codex",
    where: "Codex",
    command: "/graphify .",
    usage: "Run the optional installed Graphify command for the current repository, then verify its inferred edges against source files.",
    prerequisites: "Graphify 0.9.50 installed in Codex.",
    result: "Creates graph output or reports why the optional tool could not run.",
    sources: [{ file: "vibies-session-8.html", location: "slide 19" }],
  },
  {
    id: "node-version",
    title: "Check the Node.js version",
    topic: "Node and Next.js",
    where: "shell",
    command: "node --version",
    usage: "Confirm the runtime before installing or running a project. Current Vibies development uses Node.js 24.",
    prerequisites: "Node.js installed.",
    result: "Prints the installed Node.js version or stops with a command-not-found error.",
    sources: [
      { file: "vibies-session-7.html", location: "slide 2" },
      { file: "vibies-session-catchup.html", location: "slide 9" },
    ],
    guide: { label: "Run Vibies locally", href: `${repository}/README.md#run-the-demo-locally` },
  },
  {
    id: "npm-version",
    title: "Check the npm version",
    topic: "Node and Next.js",
    where: "shell",
    command: "npm --version",
    usage: "Confirm that npm is available before you install or run a project.",
    prerequisites: "Node.js with npm installed.",
    result: "Prints the installed npm version or stops with a command-not-found error.",
    sources: [
      { file: "vibies-session-7.html", location: "slide 2" },
      { file: "vibies-session-catchup.html", location: "slide 9" },
    ],
  },
  {
    id: "npm-list-scripts",
    title: "List project npm scripts",
    topic: "Node and Next.js",
    where: "shell",
    command: "npm run",
    usage: "See the named commands that the current package.json makes available.",
    prerequisites: "The current folder contains package.json.",
    result: "Prints the available npm scripts or reports that the package file is missing.",
    sources: [{ file: "vibies-session-7.html", location: "slide 5" }],
  },
  {
    id: "npm-run-dev",
    title: "Start the local development server",
    topic: "Node and Next.js",
    where: "shell",
    command: "npm run dev",
    usage: "Start the project's development script and keep this terminal open. Use the local URL that it prints.",
    prerequisites: "Dependencies installed in the project folder. Current Vibies requires Node.js 24.",
    result: "Starts the local Next.js server or prints the error that stopped it. Press Ctrl+C to stop the server.",
    sources: [
      { file: "vibies-session-7.html", location: "slides 5 and 7" },
      { file: "vibies-session-catchup.html", location: "slide 20" },
    ],
    guide: { label: "Run Vibies locally", href: `${repository}/README.md#run-the-demo-locally` },
  },
  {
    id: "npm-run-build",
    title: "Build the production application",
    topic: "Node and Next.js",
    where: "shell",
    command: "npm run build",
    usage: "Run the production build check before a Preview or pull request is ready.",
    prerequisites: "Dependencies installed in the project folder. Current Vibies requires Node.js 24.",
    result: "Creates a production build or exits with the build error that must be fixed.",
    sources: [
      { file: "vibies-session-8.html", location: "slides 2 and 5" },
      { file: "vibies-session-catchup.html", location: "slides 24 and 30" },
    ],
    guide: { label: "Run Vibies checks", href: `${repository}/README.md#run-the-demo-locally` },
  },
  {
    id: "next-scaffold-pinned",
    title: "Create the dated practice Next.js app",
    topic: "Node and Next.js",
    where: "shell",
    command: "npx create-next-app@16.3.2 [app name] --use-npm --yes",
    usage: "Use this exact pinned version only for the Session 7 and catch-up personal exercise. Current Vibies is already scaffolded.",
    prerequisites: "A new empty parent folder and Node.js 20.9 or newer. Current Vibies development requires Node.js 24.",
    placeholders: replaceBrackets,
    result: "Creates the dated practice application folder or stops with the scaffold error.",
    sources: [
      { file: "vibies-session-7.html", location: "slide 2, app name replaced" },
      { file: "vibies-session-catchup.html", location: "slide 12, app name replaced" },
    ],
    guide: { label: "Current Vibies setup", href: `${repository}/README.md#run-the-demo-locally` },
  },
  {
    id: "vercel-first-deployment",
    title: "Deploy a Next.js project with Vercel",
    topic: "Deployment and database",
    where: "browser",
    usage: "Import the intended GitHub repository in Vercel, confirm the detected Next.js settings, and verify the deployed URL.",
    prerequisites: "A safe public repository with a passing production build.",
    result: "Creates a deployment and URL, or shows the build or configuration error that stopped it.",
    sources: [
      { file: "vibies-session-8.html", location: "slides 8 to 10" },
      { file: "vibies-session-catchup.html", location: "slide 24" },
    ],
    guide: { label: "Supabase and Vercel setup", href: `${repository}/docs/SUPABASE-SETUP.md#5-configure-and-deploy-with-vercel` },
  },
  {
    id: "vercel-preview-proof",
    title: "Prove a change on its Preview",
    topic: "Deployment and database",
    where: "browser",
    usage: "Open the Preview for the latest feature-branch commit and check every acceptance criterion before merge.",
    prerequisites: "A feature branch and pull request with a completed Preview deployment.",
    result: "Produces browser evidence for the reviewed change or identifies a criterion that still fails.",
    sources: [
      { file: "vibies-session-8.html", location: "slides 11 to 15" },
      { file: "vibies-session-catchup.html", location: "slides 32 to 34" },
    ],
    guide: { label: "Vibies merge gate", href: `${repository}/CONTRIBUTING.md#the-merge-gate-six-checks` },
  },
  {
    id: "supabase-demo-setup",
    title: "Set up the Supabase demo",
    topic: "Deployment and database",
    where: "SQL Editor",
    usage: "Use the maintained setup guide and complete SQL files. Inspect the database first and stop on an unexpected table, owner, policy, or grant.",
    prerequisites: "A Supabase project that contains no real Vibies data.",
    result: "Creates and verifies the synthetic read-only demo, or stops at the failed safety check.",
    sources: [{ file: "vibies-session-9.html", location: "slides 13 to 17; partial classroom SQL replaced by maintained guide" }],
    guide: { label: "Supabase demo setup", href: `${repository}/docs/SUPABASE-SETUP.md` },
  },
  {
    id: "database-migration-deployment",
    title: "Deploy reviewed database migrations",
    topic: "Deployment and database",
    where: "browser",
    usage: "Follow the repository migration order for local proof, a GitHub-linked Preview, reviewed merge, and Production verification.",
    prerequisites: "A reviewed database change on a feature branch.",
    result: "Records separate migration and application deployment receipts, or stops at the failed layer.",
    sources: [{ file: "vibies-session-9.html", location: "slides 14 to 17; classroom setup redirected to current workflow" }],
    guide: { label: "Database deployment", href: `${repository}/docs/DATABASE-DEPLOYMENT.md` },
  },
  {
    id: "access-setup-guide",
    title: "Set up Vibies access",
    topic: "Deployment and database",
    where: "browser",
    usage: "Follow the maintained guide for database access, GitHub sign-in, the Instructor, recovery, and environment-specific proof.",
    prerequisites: "Authority to configure the intended Supabase, GitHub, and Vercel environment.",
    result: "Completes the bounded access setup and checks, or stops at the first unmet safety condition.",
    sources: [{ file: "vibies-session-10.html", location: "slides 3, 4, 11, and 18" }],
    guide: { label: "Access setup", href: `${repository}/docs/ACCESS-SETUP.md` },
  },
  {
    id: "project-publishing-setup",
    title: "Set up Personal Project publishing",
    topic: "Deployment and database",
    where: "browser",
    usage: "Use the maintained Preview setup and proof procedure for project ownership, publication, and signed-out checks.",
    prerequisites: "An approved feature Preview and authority to configure its GitHub App and server settings.",
    result: "Completes the Personal Project proof or stops at the failed ownership, access, or publication check.",
    sources: [{ file: "vibies-session-10.html", location: "slides 5, 10, 14, 15, and 18; SQL excerpt replaced by maintained guide" }],
    guide: { label: "Personal Project setup", href: `${repository}/docs/PROJECT-SETUP.md` },
  },
];

export const wikiTopics = [...new Set(wikiEntries.map((entry) => entry.topic))];

export function filterWiki(query: string, topic: string): WikiEntry[] {
  const words = query.trim().toLowerCase();
  const selectedTopic = topic.trim();

  return wikiEntries.filter((entry) =>
    (!selectedTopic || entry.topic === selectedTopic) &&
    (!words || [entry.title, entry.command, entry.keys, entry.usage, entry.prerequisites, entry.placeholders, entry.result]
      .some((value) => value?.toLowerCase().includes(words))),
  );
}
